// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJhV523MQNZ2IzFN7BYjIHR0xZ2_ZsTU',
    appId: '1:275691630070:web:6129f68afa686cc8d26bd7',
    messagingSenderId: '275691630070',
    projectId: 'mealbook-78c31',
    authDomain: 'mealbook-78c31.firebaseapp.com',
    storageBucket: 'mealbook-78c31.appspot.com',
    measurementId: 'G-47NGNBML23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEje4B5ftZQGWdwdSQobVxFEbm_d6DD4I',
    appId: '1:275691630070:android:c791c3b0e6533156d26bd7',
    messagingSenderId: '275691630070',
    projectId: 'mealbook-78c31',
    storageBucket: 'mealbook-78c31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBorNnw_u2vM0hhEISOxYwuW2R_JcUkXdA',
    appId: '1:275691630070:ios:78e0e1ca069628d9d26bd7',
    messagingSenderId: '275691630070',
    projectId: 'mealbook-78c31',
    storageBucket: 'mealbook-78c31.appspot.com',
    iosBundleId: 'com.example.mealBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBorNnw_u2vM0hhEISOxYwuW2R_JcUkXdA',
    appId: '1:275691630070:ios:78e0e1ca069628d9d26bd7',
    messagingSenderId: '275691630070',
    projectId: 'mealbook-78c31',
    storageBucket: 'mealbook-78c31.appspot.com',
    iosBundleId: 'com.example.mealBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpJhV523MQNZ2IzFN7BYjIHR0xZ2_ZsTU',
    appId: '1:275691630070:web:e38d6b7ab48dc942d26bd7',
    messagingSenderId: '275691630070',
    projectId: 'mealbook-78c31',
    authDomain: 'mealbook-78c31.firebaseapp.com',
    storageBucket: 'mealbook-78c31.appspot.com',
    measurementId: 'G-T7QMN4RE62',
  );

}