// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm_tnCHz6-MGu3fU4DgKtRt54HZC4X2Ec',
    appId: '1:48308461876:web:c7b0b7225d3af241854561',
    messagingSenderId: '48308461876',
    projectId: 'meal-book-1d355',
    authDomain: 'meal-book-1d355.firebaseapp.com',
    storageBucket: 'meal-book-1d355.appspot.com',
    measurementId: 'G-E95V6GGGJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5bJ4HD9KnjbQZ61R5vG6uOvepEiYVto',
    appId: '1:48308461876:android:3311077beae92d59854561',
    messagingSenderId: '48308461876',
    projectId: 'meal-book-1d355',
    storageBucket: 'meal-book-1d355.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0upvfVK_DpUyZAiv0hfKgO9eIu1z0g6Q',
    appId: '1:48308461876:ios:12c603eeab66631b854561',
    messagingSenderId: '48308461876',
    projectId: 'meal-book-1d355',
    storageBucket: 'meal-book-1d355.appspot.com',
    iosBundleId: 'com.example.mealBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0upvfVK_DpUyZAiv0hfKgO9eIu1z0g6Q',
    appId: '1:48308461876:ios:674545feaaa4e041854561',
    messagingSenderId: '48308461876',
    projectId: 'meal-book-1d355',
    storageBucket: 'meal-book-1d355.appspot.com',
    iosBundleId: 'com.example.mealBook.RunnerTests',
  );
}
